name: SQBot
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13
  - pip
  - pip:
    - flask
    - python-dotenv
    - pinecone
    - langchain
    - langchain-community
    - sentence-transformers
    - google-generativeai
    - openai
    - gunicorn # For running the app
